name: Build
on: [push]
jobs:
  object_calisthenics_rules:
    runs-on: ubuntu-latest
    name: Check coding conventions
    steps:
      - name: Install php
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
      - name: Checkout SDK
        uses: actions/checkout@v1
      - name: Install dependencies
        run:  composer install
      - name: Run MultiSafepay Coding Standards
        run:  vendor/bin/phpcs --standard=phpcs.ruleset.xml .
  php_unit_test:
    runs-on: ubuntu-latest
    name: PHP Unit Test with PHP version ${{ matrix.php-version }}
    strategy:
      matrix:
        php-version:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
    steps:
      - name: Install php
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom, mbstring
      - name: Checkout SDK
        uses: actions/checkout@v1
      - name: Install dependencies
        run:  composer install
      - name: Update environment file
        run: |
          cp .env.php.example .env.php
          sed -i "s/'API_KEY' => ''/'API_KEY' => '${{ secrets.API_KEY }}'/g" .env.php
      - name: Run PHPUnit tests
        run:  vendor/bin/phpunit --coverage-clover=coverage.xml
      - name: Send clover to codecov
        run: test -z "${{ secrets.CODECOV_TOKEN }}" || (bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -f "*.php" -Z -R .)
